### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#11]
- [x] Resolve outstanding "ToDo" items
  - [x] About
  - [x] Quickstart
  - [x] Account Mgmt
  - [x] AuthN
  - [x] AuthZ
  - [x] Multitenancy
  - [x] ID Site
  - [x] Reference
- [x] Close all existing feedback issues

_Reference Chapter_ 
- [x] Add information about Account Creation Email Templates
- [x] Add info about the Application API Key collection - _turns out there isn't anything else to say!_
- [x] Add info about CRUDing Account API Keys

_Account Mgmt_
- [x] Writing Re-sending the Verification Email instructions
- [x] Add info about "Customizing Emails via REST" to end of section. (It doesn't really fit anywhere else, because so many other individual sections are relevant to it)
