### ISSUE TITLE
Rewrite Quickstart to support multi-language output

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#20]
Rewrite Quickstart with the help of @bretterer and @nbarbettini to support multi-language output for REST, PHP and .NET. 

The end result here should be the same Quickstart text, except with code examples that are either REST, PHP or C#. 

This will function as a quick demo that we can then apply to the entire guide.

**Comment by jakubvul** [comment]
**Tasks**
- [x] Language-specific directories created
- [x] `..only::` directives added for all languages in `Quickstart.rst` chapter
- [x] PHP-specific additions completed by @bretterer 
- [x] Java-specific additions completed by @dogeared 
- [x] .NET-specific additions completed by @nbarbettini 
- [x] Python-specific additions completed by @rdegges 
- [x] Node.js-specific additions completed by @typerandom

**Comment by nbarbettini** [comment]
> and give you a good initial feel for the Stormpath REST API.

:question: Should this be language-specific, such as:

> and give you a good initial feel for the Stormpath .NET SDK.

**Comment by nbarbettini** [comment]
@jakubswiatczak Comments on #34.

**Comment by nbarbettini** [comment]
General question for @jakubswiatczak and @omgitstom: do we want to agree on a consistent grammatical POV here? Wasn't quite sure if I should use 2nd or 3rd person.

**Comment by nbarbettini** [comment]
@jakubswiatczak We should also probably all agree on common editor settings. I'm using Atom and it wants to use 4 spaces for tabs. I think you're using 2. That might end up causing a lot of noise in diffs. Ditto to line break style?

**Comment by nbarbettini** [comment]
w00t :tada:
